audit_header: false
title: "Whittier's Best Real Estate Training"
description: Jennifer Brown, a top Real Estate Agent in Whittier, shares her own internal real estate agent training for free. Her Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Why KW Now?
    url: http://www.kw.com/kw/TheDifference.html
  - title: Careers Worth Having
    url: http://www.kw.com/kw/careers-in-real-estate.html
  - title: Our Belief System
    url: http://www.kw.com/kw/mvvbp.html
  - title: Profit Sharing Report
    url: http://images.kw.com/kw/user_uploads/US-profit%20share%20and%20growth%20share%20white%20paper.pdf

client:
  name: Jennifer Brown
  title:
  license_number:
  about_markdown: |
    Born and raised in Whittier, CA, Jennifer brings 27 years of Real Estate experience. Her background consists of Management, Training, Education and Coaching. As a strong problem solver with a true passion for the real estate industry, she is always looking for ways to improve and take agents to the next level in their business.

    Customer service and exceeding expectations is her number one priority while providing the right team environment and resources.

    When not working she is spending time with her grandkids and her family. She loves cooking and enjoying the outdoors.
  market: Whittier
  brand: Keller Williams Realty Whittier
  brokerage:
  address: 16310 Whittier Blvd, Suite<br>Whittier, CA 90603
  phone: 562-902-5100
  phone_type: Office
  phone2: 562-577-9958
  phone2_type: Direct
  email: jbrownkw@kw.com
  url:

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how -- CLIENT BRAND -- can take your business to new heights."
    CTA_link_text: "Free Strategy Session"
    CTA_url: /contact/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.png
    CTA_title2: "GET IT FREE: The Millionaire Real Estate Agent Book"
    CTA_text2: "Let's visit about how to help you be more successful at your San Diego real estate career. When we meet you'll get a free copy of the best-selling book The Millionaire Real Estate Agent: It's Not About the Money...It's About Being the Best You Can Be! Absolutely no-obligation. It's yours to keep."
    CTA_link_text2: "Contact Me"
    CTA_url2: /contact/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Whittier Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Whittier Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional Whittier Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Whittier, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Whittier Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#b40101'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
